import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navigation from '../components/navigation';
import Header from '../components/header';
import ListenedBookBox from '../components/listenedBookBox';
import RecentlyPlayedBox from '../components/recentlyPlayedBox';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navigation />
        <div className={styles.components}>
          <Header />
          <ListenedBookBox />
          <RecentlyPlayedBox />
        </div>
      </main>
    </div>
  );
};

export default Home;
